stages:
  - build
  - deploy
  
build:
  stage: build
  image : maven:latest
  script:
      - mvn package
  artifacts:
    untracked: true



deploy:
  services:
    - docker
  dependencies:
    - build
  image: docker:latest
  stage: deploy
  script:
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - cd exemple-service-1/
      #- ./mvnw clean install
      - docker build -f src/main/docker/Dockerfile.jvm -t movie-cupidon-backend/example-service-1 .
      - docker tag movie-cupidon-backend/example-service-1 bayar4b/movie-cupidon-backend_example-service-1:latest 
      - docker push bayar4b/movie-cupidon-backend_example-service-1:latest

      - cd ../
      - docker build -f api-gateway-kong/src/main/docker/Dockerfile -t movie-cupidon-backend/api-gateway:latest .
      - docker tag movie-cupidon-backend/api-gateway:latest bayar4b/movie-cupidon-backend_api-gateway:latest
      - docker push bayar4b/movie-cupidon-backend_api-gateway:latest



