image: maven:latest
stages:
  - build
  - deploy




build:
  stage: build
  script:
    - mvn package -Dquarkus.container-image.username=$DOCKER_USERNAME -Dquarkus.container-image.password=$DOCKER_PASSWORD -Dquarkus.container-image.push=false -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=latest
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.repository/"
  cache:
    key: maven
    paths: [.repository/]
  artifacts:
    paths:
      - lobby-service/target/
      - sample-selection-service/target/

deploy:
  stage: deploy
  script:
    - mvn package -DskipTests -Dquarkus.container-image.username=$DOCKER_USERNAME -Dquarkus.container-image.password=$DOCKER_PASSWORD -Dquarkus.container-image.push=true -Dquarkus.container-image.build=false -Dquarkus.container-image.tag=latest
  only:
    - master
