stages:
  - build
  - deploy
  
build:
  stage: build
  image : maven:latest
  script:
      - mvn package
  artifacts:
    untracked: true

deploy:
  dependencies:
    - build
  image: docker:latest
  stage: deploy
  script:
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - cd lobby-service/
      - docker build -f src/main/docker/Dockerfile.jvm -t moviecupidon/lobby-service:latest .
      - docker tag moviecupidon/lobby-service:latest bayar4b/moviecupidon/lobby-service:latest
      - docker push bayar4b/moviecupidon/lobby-service:latest
      - cd ..
      - cd sample-selection-service/
      - docker build -f src/main/docker/Dockerfile.jvm -t moviecupidon/sample-selection-service:latest .
      - docker tag moviecupidon/sample-selection-service:latest bayar4b/moviecupidon/sample-selection-service:latest
      - docker push bayar4b/moviecupidon/sample-selection-service:latest
      - cd ..
  # only:
  #   - master
