stages:
  - build
  - deploy

build:
  image: maven:latest
  stage: build
  script:
    - mvn install
    - mvn install -Ppackage-docker-image -Ddocker_username=$DOCKER_USERNAME -Ddocker_password=$DOCKER_PASSWORD 


deploy:
  image: docker:latest
  stage: deploy
  script:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
    - docker pull bayar4b/example-service-1
    - docker run -p 10080:8080 --name=example-service-1 unige/example-service-1

