stages:
  - build
  - deploy
  
build:
  stage: build
  image : maven:latest
  script:
      - mvn package
  artifacts:
    untracked: true

deploy:
  dependencies:
    - build
  image: docker:latest
  stage: deploy
  script:
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      # - cd exemple-service-1/
      - docker build -f lobby-service/src/main/docker/Dockerfile.jvm -t movieCupidon/lobby-service:latest .
      - docker push movieCupidon/lobby-service:latest
      - docker build -f sample-selection-service/src/main/docker/Dockerfile.jvm -t movieCupidon/sample-selection-service:latest .
      - docker push movieCupidon/sample-selection-service:latest
  # only:
  #   - master
