stages:
  - build
  - deploy



build:
  stage: build
  image : maven:latest
  variables:
      MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.repository/"
  cache:
      key: maven
      paths: [.repository/]
  script:
      - mvn package
  artifacts:
    untracked: true



deploy:
  dependencies:
    - build
  image: docker:latest
  stage: deploy
  script:
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - cd exemple-service-1/
      #- ./mvnw clean install

      - docker build -f src/main/docker/Dockerfile.jvm -t movie-cupidon-backend/example-service-1 .
      - docker tag movie-cupidon-backend/example-service-1 bayar4b/movie-cupidon-backend_example-service-1:latest 
      - docker push bayar4b/movie-cupidon-backend_example-service-1:latest


      #- cd ../api-gateway-kong/src/main/docker/
      #- docker build -f Dockerfile -t movie-cupidon-backend/api-gateway .
      #- docker tag movie-cupidon-backend/api-gateway bayar4b/movie-cupidon-backend_api-gateway:latest 
      #- docker push bayar4b/movie-cupidon-backend_api-gateway:latest



