apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webui-service
            port:
              number: 80
      - path: /lobby/
        pathType: Prefix
        backend:
          service:
            name: lobby-service
            port:
              number: 8080
