apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app : lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      containers:
      - name: lobby
        image: bayar4b/movie-cupidon-backend_lobby-service:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: lobby-service
spec:
  selector:
    app: lobby
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080